version: "3.8"
services:
  web:
    build:
      context: .
      target: development
    ports:
      - 127.0.0.1:5000:5000
    env_file:
      - .env
    volumes:
    - type: bind
      source: .
      target: /code

